In [2]:
import numpy as np

In [26]:
A = np.ones((3,3))

In [36]:
B = A@A
C = A / B
print(C)

[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]


In [37]:
from sympy import symbols, Eq, Function, dsolve
f, g = symbols("f g", cls=Function)
x = symbols("x")
eqs = [Eq(f(x).diff(x), g(x)), Eq(g(x).diff(x), f(x))]
dsolve(eqs, [f(x), g(x)])
dsolve(eqs, [f(x), g(x)], ics={f(0): 1, g(2): 3})

[Eq(f(x), (1 + 3*exp(2))*exp(x)/(1 + exp(4)) - (-exp(4) + 3*exp(2))*exp(-x)/(1 + exp(4))),
 Eq(g(x), (1 + 3*exp(2))*exp(x)/(1 + exp(4)) + (-exp(4) + 3*exp(2))*exp(-x)/(1 + exp(4)))]